export const SET_LIKELIST = 'SET_LIKELIST'

export const SET_LIKEBOOK_LIST = 'SET_LIKEBOOK_LIST'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_CURRENTPLAY_INDEX = 'SET_CURRENTPLAY_INDEX'